export const WORDS_DB = {
  "easy": {
    "cores": ["Azul", "Verde", "Vermelho", "Amarelo", "Rosa"],
    "animais": ["Cachorro", "Gato", "Coelho", "Pássaro", "Peixe"],
    "transporte": ["Carro", "Ônibus", "Trem", "Bicicleta", "Avião"],
    "estação do ano": ["Verão", "Inverno", "Outono", "Primavera"],
    "empregos": ["Garçom", "Padeiro", "Fazendeiro", "Pintor", "Bombeiro"],
    "frutas": ["Uva", "Pera", "Manga", "Melancia", "Kiwi"],
    "esportes": ["Futebol", "Basquete", "Tênis", "Natação", "Vôlei"],
    "mobília": ["Cama", "Sofá", "Mesa", "Cadeira"],
    "instrumentos musicais": ["Violino", "Piano", "Guitarra", "Flauta"],
    "flores": ["Rosa", "Orquídea", "Lírio", "Girassol", "Tulipa"],
    "países": ["Brasil", "Estados Unidos", "França", "Japão"],
    "bebidas": ["Café", "Chá", "Suco", "Refrigerante", "Água"],
    "doces": ["Bolo", "Sorvete", "Chocolate", "Pudim", "Gelatina"],
    "partes do corpo": ["Cabeça", "Braço", "Perna", "Pé", "Mão"],
    "televisão": ["Série", "Filme", "Documentário", "Novela"],
    "eletrodomésticos": ["Geladeira", "Fogão", "Máquina de lavar", "Liquidificador"],
    "planetário": ["Mercúrio", "Vênus", "Terra", "Marte", "Júpiter"],
    "instrumentos de escrita": ["Caneta", "Lápis", "Canetinha", "Marca-texto"],
    "comidas": ["Arroz", "Feijão", "Macarrão", "Pão", "Pizza"],
    "meios de comunicação": ["Jornal", "Revista", "Rádio", "Internet", "Livro"],
    "itens de vestuário": ["Camisa", "Calça", "Vestido", "Sapato", "Boné"],
    "hobbies": ["Pintura", "Dança", "Canto", "Leitura", "Culinária"],
    "destinos de viagem": ["Praia", "Montanha", "Cidade", "Camping", "Interior"],
    "elementos naturais": ["Água", "Fogo", "Terra", "Ar", "Sol"],
    "disciplinas escolares": ["Matemática", "História", "Geografia", "Ciências", "Educação Física"]
  },
  "medium": {
    "ferramentas": ["Martelo", "Chave de fenda", "Serra elétrica", "Furadeira", "Alicate"],
    "disciplinas escolares": ["História", "Matemática", "Biologia", "Física", "Química"],
    "esportes radicais": ["Surfe", "Escalada", "Rafting", "Bungee jumping", "Paraquedismo"],
    "ramo médico": ["Dermatologia", "Pediatria", "Oftalmologia", "Cardiologia", "Ginecologia"],
    "compositores clássicos": ["Mozart", "Beethoven", "Chopin", "Vivaldi", "Bach"],
    "obras literárias": ["Dom Quixote", "Moby Dick", "Dom Casmurro", "A Divina Comédia", "Hamlet"],
    "movimentos artísticos": ["Renascimento", "Impressionismo", "Cubismo", "Surrealismo", "Barroco"],
    "pensadores influentes": ["Platão", "Aristóteles", "Sócrates", "Descartes", "Nietzsche"],
    "estilos de dança": ["Tango", "Ballet", "Hip-hop", "Flamenco", "Salsa"],
    "instrumentos de corda": ["Violino", "Violoncelo", "Guitarra", "Contrabaixo", "Viola"],
    "elementos químicos": ["Oxigênio", "Carbono", "Nitrogênio", "Ferro", "Hidrogênio"],
    "artistas renomados": ["van Gogh", "Picasso", "da Vinci", "Kahlo", "Dalí"],
    "conceitos matemáticos": ["Álgebra", "Geometria", "Cálculo", "Trigonometria", "Estatística"],
    "correntes filosóficas": ["Empirismo", "Racionalismo", "Idealismo", "Positivismo", "Pragmatismo"],
    "gêneros literários": ["Poesia", "Romance", "Drama", "Ficção científica", "Biografia"],
    "movimentos sociais": ["Feminismo", "Direitos civis", "Ecologismo", "Abolicionismo", "Sindicalismo"],
    "estilos arquitetônicos": ["Gótico", "Neoclássico", "Art Nouveau", "Barroco", "Moderno"],
    "compositores contemporâneos": ["Zimmer", "Williams", "Tiersen", "Morricone", "Bennett"],
    "teorias científicas": ["Big Bang", "Evolução", "Física Quântica", "Teoria do Caos", "Relatividade"],
    "estilos de arte": ["Realismo", "Abstracionismo", "Cubismo", "Surrealismo", "Expressionismo"],
    "compositores românticos": ["Schubert", "Tchaikovsky", "Liszt", "Chopin", "Verdi"],
    "movimentos literários": ["Romantismo", "Realismo", "Modernismo", "Naturalismo", "Simbolismo"],
    "jogos de tabuleiro": ["Xadrez", "Dama", "Dominó", "War", "Detetive"],
    "gêneros cinematográficos": ["Suspense", "Aventura", "Fantasia", "Romance", "Mistério"],
    "teorias de aprendizagem": ["Construtivismo", "Behaviorismo", "Cognitivismo", "Humanismo", "Conectivismo"],
    "filósofos contemporâneos": ["Slavoj Žižek", "Judith Butler", "Noam Chomsky", "Martha Nussbaum", "Peter Singer"]
  },
  "hard": {
    "tecnologias avançadas": ["Inteligência Artificial", "Computação Quântica", "Nanotecnologia", "Biônica", "Realidade Virtual"],
    "fenômenos astronômicos": ["Buraco Negro", "Quasar", "Asteróide", "Galáxia", "Nebulosa"],
    "desastres naturais": ["Tsunami", "Furacão", "Terremoto", "Erupção Vulcânica", "Tornado"],
    "princípios econômicos avançados": ["Globalização", "Economia de Escambo", "Superávit Primário", "Política Fiscal", "Capital Intelectual"],
    "episódios históricos": ["Guerra dos Cem Anos", "Guerra Civil Americana", "Primeira Guerra Mundial", "Segunda Guerra Mundial", "Guerra Fria"],
    "violations de direitos": ["Direito à Liberdade de Expressão", "Direito à Vida", "Direito à Educação", "Direito à Moradia", "Direito à Igualdade"],
    "ataques genocidas": ["Genocídio Armênio", "Holocausto", "Genocídio de Ruanda", "Guerra do Iraque", "Genocídio de Darfur"],
    "teoremas matemáticos": ["Teorema de Pitágoras", "Teorema de Tales", "Teorema Fundamental do Cálculo", "Teorema de Fermat", "Teorema de Bolzano"],
    "cientistas renomados": ["Isaac Newton", "Marie Curie", "Albert Einstein", "Stephen Hawking", "Nikola Tesla"],
    "movimentos revolucionários": ["Revolução Industrial", "Movimento dos Direitos Civis", "Primavera Árabe", "Revolução Cultural Chinesa", "Revolução de Outubro"],
    "batalhas históricas": ["Stalingrado", "Waterloo", "Gettysburg", "Thermopylae", "Hastings"],
    "filósofos clássicos": ["Platão", "Aristóteles", "Sócrates", "Sêneca", "Cícero"],
    "teorias psicológicas": ["Psicanálise", "Behaviorismo", "Gestalt", "Teoria da Inteligência Multiplas", "Teoria da Personalidade"],
    "conceitos sociológicos": ["Estratificação Social", "Mobilidade Social", "Segregação Racial", "Fenômeno de Grupo", "Conflito Social"],
    "doenças pandêmicas": ["Peste Negra", "Gripe Espanhola", "COVID-19", "Pandemia de HIV/AIDS", "Pandemia de Cólera"],
    "princípios de física avançada": ["Princípio da Incerteza", "Princípio da Relatividade", "Princípio da Conservação da Energia", "Princípio de Arquimedes", "Princípio de Bernoulli"],
    "correntes literárias": ["Modernismo", "Pós-Modernismo", "Realismo Mágico", "Naturalismo", "Expressionismo"],
    "antigos impérios": ["Império Romano", "Império Mongol", "Império Britânico", "Império Otomano", "Império Inca"],
    "línguas antigas": ["Latim", "Grego Antigo", "Sânscrito", "Hebraico Antigo", "Egípcio Antigo"],
    "desenvolvimentos científicos": ["Descoberta da Penicilina", "Modelo Atômico de Bohr", "Leis de Kepler", "Teoria do Eletromagnetismo", "Leis de Mendel"],
    "teorias de filosofia política": ["Contratualismo", "Utilitarismo", "Liberalismo", "Comunismo", "Anarquismo"],
    "obras literárias canônicas": ["Dom Quixote", "Os Miseráveis", "Guerra e Paz", "Ulisses", "Cem Anos de Solidão"],
    "teorias de administração": ["Teoria Clássica", "Teoria das Relações Humanas", "Administração por Objetivos", "Administração Científica", "Gestão da Qualidade Total"]
  },
  "veryHard": {
    "complicações médicas raras": ["Encefalomielite", "Mielodisplasia", "Esclerose sistêmica", "Neurossífilis", "Poliomielite"],
    "teoremas matemáticos avançados": ["Fermat", "Gödel", "Cantor", "Euler", "Poincaré"],
    "instrumentos musicais complexos": ["Theremim", "Ondes Martenot", "Clavicórdio", "Serrote musical", "Órgão de tubos"],
    "termos de astrofísica avançada": ["Buraco negro supermassivo", "Hipernova", "Quasar", "Pulsar", "Efeito Shapiro"],
    "desordens psiquiátricas complexas": ["Personalidade esquizotípica", "Transtorno dissociativo de identidade", "Personalidade borderline", "Transtorno bipolar do humor", "Esquizofrenia"],
    "gêneros literários obscuros": ["Dadaísmo", "Oulipo", "Ficção especulativa", "Literatura transgressiva", "Realismo mágico"],
    "termos de engenharia aeroespacial": ["Aerodinâmica", "Propulsão a jato", "Mecânica orbital", "Materiais compósitos aeroespaciais", "Sistema de controle de voo"],
    "doenças autoimunes raras": ["Granulomatose de Wegener", "Síndrome de Goodpasture", "Doença de Behçet", "Doença de Addison", "Púrpura trombocitopênica idiopática"],
    "estilos arquitetônicos complexos": ["Brutalismo", "Deconstructivismo", "Construtivismo russo", "High-tech", "Expressionismo"],
    "teorias políticas obscuras": ["Anarquismo insurrecionalista", "Municipalismo libertário", "Autonomismo", "Neomarxismo", "Ecofascismo"],
    "conceitos de psicanálise profunda": ["Complexo de Édipo negativo", "Narcisismo primário", "Superego", "Pulsão de morte", "Identificação projetiva"],
    "termos de linguística avançada": ["Sociolinguística", "Fonologia generativa", "Teoria da relevância", "Morfologia lexical", "Sintaxe minimalista"],
    "teorias de antropologia complexa": ["Estruturalismo", "Funcionalismo", "Culturalismo", "Teoria do conflito", "Antropologia simbólica"],
    "invenções tecnológicas revolucionárias": ["Transístor", "Internet", "Penicilina", "Vacina", "Impressora 3D"],
    "paradigmas científicos disruptivos": ["Teoria da relatividade", "Teoria do Big Bang", "Teoria da evolução", "Teoria quântica", "Teoria heliocêntrica"],
    "teorias de filosofia política complexas": ["Utilitarismo", "Contratualismo", "Hedonismo", "Existencialismo", "Anarquismo ontológico"],
    "movimentos artísticos experimentais": ["Arte conceitual", "Arte minimalista", "Arte performática", "Arte cinética", "Arte cibernética"],
    "termos de biotecnologia avançada": ["Edição de genoma", "Clonagem terapêutica", "Biorreator", "Biotecnologia vegetal", "Terapia gênica"],
    "conceitos de filosofia da mente complexos": ["Dualismo interativo", "Funcionalismo", "Materialismo eliminativo", "Epifenomenalismo", "Neutral monism"],
    "crises econômicas históricas": ["Grande Depressão", "Crise do Petróleo", "Crise financeira de 2008", "Crise do subprime"],
    "desastres naturais": ["Terremoto de Lisboa", "Erupção do Monte Vesúvio", "Tsunami no Oceano Índico", "Furacão Katrina"],
    "teorias quânticas": ["Entrelaçamento quântico", "Superposição quântica", "Emaranhamento quântico", "Túnel quântico", "Teorema de Bell"],
    "livros filosóficos complexos": ["Ser e Tempo", "O Ser e o Nada", "Fenomenologia do Espírito", "Investigações Lógicas"],
    "guerras modernas": ["Segunda Guerra Mundial", "Guerra do Vietnã", "Guerra do Golfo", "Guerra Civil Síria"],
    "problemas matemáticos não resolvidos": ["Conjectura de Goldbach", "Conjectura de Hodge", "Hipótese de Riemann", "Conjectura de Poincaré"]
  }
};


export type WordDBDifficulty = keyof typeof WORDS_DB

export type WordDBTopic = keyof typeof WORDS_DB[WordDBDifficulty]