export const WORDS_DB = {
  "facil": {
    "alimentos": ["Maçã", "Banana", "Laranja", "Morango", "Abacaxi"],
    "cores": ["Azul", "Verde", "Vermelho", "Amarelo", "Rosa"],
    "animais": ["Cachorro", "Gato", "Coelho", "Pássaro", "Peixe"],
    "transporte": ["Carro", "Ônibus", "Trem", "Bicicleta", "Avião"],
    "estação do ano": ["Verão", "Inverno", "Outono", "Primavera", "Monção"],
    "profissões": ["Médico", "Professor", "Advogado", "Engenheiro", "Dentista"],
    "frutas": ["Uva", "Pera", "Manga", "Melancia", "Kiwi"],
    "esportes": ["Futebol", "Basquete", "Tênis", "Natação", "Vôlei"],
    "mobília": ["Cama", "Sofá", "Mesa", "Cadeira", "Armário"],
    "instrumentos musicais": ["Violino", "Piano", "Guitarra", "Flauta", "Bateria"],
    "flores": ["Rosa", "Orquídea", "Lírio", "Girassol", "Tulipa"],
    "países": ["Brasil", "Estados Unidos", "França", "Japão", "Austrália"],
    "bebidas": ["Café", "Chá", "Suco", "Refrigerante", "Água"],
    "doces": ["Bolo", "Sorvete", "Chocolate", "Pudim", "Gelatina"],
    "partes do corpo": ["Cabeça", "Braço", "Perna", "Pé", "Mão"],
    "televisão": ["Série", "Filme", "Documentário", "Novela", "Reality show"],
    "eletrodomésticos": ["Geladeira", "Fogão", "Máquina de lavar", "Liquidificador", "Micro-ondas"],
    "planetário": ["Mercúrio", "Vênus", "Terra", "Marte", "Júpiter"],
    "instrumentos de escrita": ["Caneta", "Lápis", "Canetinha", "Marca-texto", "Giz"]
  },
  "medio": {
    "ferramentas": ["Martelo", "Chave de fenda", "Serra elétrica", "Furadeira", "Alicate"],
    "disciplinas escolares": ["História", "Matemática", "Biologia", "Física", "Química"],
    "profissões": ["Médico", "Advogado", "Engenheiro", "Professor", "Arquiteto"],
    "esportes radicais": ["Surfe", "Paraquedismo", "Escalada", "Rafting", "Bungee jumping"],
    "medicina": ["Cardiologia", "Dermatologia", "Ginecologia", "Pediatria", "Oftalmologia"],
    "compositores clássicos": ["Mozart", "Beethoven", "Bach", "Chopin", "Vivaldi"],
    "literatura clássica": ["Dom Quixote", "Moby Dick", "Hamlet", "Dom Casmurro", "A Divina Comédia"],
    "movimentos artísticos": ["Renascimento", "Arte Barroca", "Impressionismo", "Cubismo", "Surrealismo"],
    "filósofos famosos": ["Platão", "Aristóteles", "Nietzsche", "Sócrates", "Descartes"],
    "estilos de dança": ["Salsa", "Tango", "Ballet", "Hip-hop", "Flamenco"],
    "instrumentos de corda": ["Violino", "Viola", "Violoncelo", "Contrabaixo", "Guitarra"],
    "elementos químicos": ["Oxigênio", "Hidrogênio", "Carbono", "Nitrogênio", "Ferro"],
    "artistas renomados": ["da Vinci", "van Gogh", "Picasso", "Kahlo", "Dalí"],
    "conceitos matemáticos": ["Álgebra", "Geometria", "Cálculo", "Trigonometria", "Estatística"],
    "correntes filosóficas": ["Existencialismo", "Empirismo", "Racionalismo", "Idealismo", "Positivismo"],
    "gêneros literários": ["Poesia", "Romance", "Drama", "Ficção científica", "Biografia"],
    "movimentos sociais": ["Feminismo", "Direitos civis", "Movimento LGBTQ+", "Abolicionismo", "Ecologismo"],
    "estilos arquitetônicos": ["Gótico", "Barroco", "Art Nouveau", "Neoclássico", "Modernismo"],
    "compositores contemporâneos": ["Hans Zimmer", "John Williams", "Ennio Morricone", "Yann Tiersen", "Richard Bennett"],
    "teorias científicas": ["Teoria da Relatividade", "Big Bang", "Evolução", "Física Quântica", "Teoria do Caos"],
    "estilos de arte": ["Realismo", "Impressionismo", "Abstracionismo", "Cubismo", "Surrealismo"],
    "compositores românticos": ["Chopin", "Schubert", "Tchaikovsky", "Verdi", "Liszt"],
    "movimentos literários": ["Romantismo", "Realismo", "Modernismo", "Naturalismo", "Simbolismo"],
    "jogos de tabuleiro": ["Xadrez", "Dama", "War", "Dominó", "Detetive"],
    "gêneros cinematográficos": ["Suspense", "Aventura", "Fantasia", "Romance", "Mistério"],
    "teorias de aprendizagem": ["Behaviorismo", "Construtivismo", "Humanismo", "Cognitivismo", "Conectivismo"],
    "filósofos contemporâneos": ["Slavoj Žižek", "Judith Butler", "Noam Chomsky", "Martha Nussbaum", "Peter Singer"],
    "conflitos históricos": ["Segunda Guerra", "Guerra Fria", "Guerra do Vietnã", "Revolução Russa", "Guerra Civil Americana"],
    "religiao": ["Cristianismo", "Islamismo", "Hinduísmo", "Budismo", "Judaísmo"],
  },
  "dificil": {
    "termos médicos": ["Eletroencefalograma", "Anticonstitucionalidade", "Otorrinolaringologista", "Desoxirribonucleico", "Imunofluorescência"],
    "termos científicos": ["Fotossíntese", "Eletromagnetismo", "Cinemática", "Mitocôndria", "Estrutura molecular"],
    "teorias filosóficas": ["Existencialismo", "Fenomenologia", "Dialética", "Construtivismo", "Empirismo"],
    "conceitos matemáticos avançados": ["Topologia", "Análise complexa", "Teoria dos Números", "Álgebra Abstrata", "Teoria das Probabilidades"],
    "autores clássicos": ["Dostoiévski", "Tolstói", "Proust", "Machado de Assis", "Kafka"],
    "termos jurídicos complexos": ["Concomitância", "Coação", "Concussão", "Consumatum est", "Ex tunc"],
    "figuras históricas influentes": ["Napoleão Bonaparte", "Cleópatra", "Genghis Khan", "Joana d'Arc", "Nelson Mandela"],
    "palavras em latim": ["Ad hoc", "In vitro", "Prima facie", "Sine qua non", "Vice-versa"],
    "doenças raras": ["Esclerose lateral amiotrófica", "Síndrome de Guillain-Barré", "Hanseníase", "Fibrose cística", "Doença de Huntington"],
    "compositores eruditos": ["Johann Sebastian Bach", "Wolfgang Amadeus Mozart", "Ludwig van Beethoven", "Johannes Brahms", "Franz Schubert"],
    "termos de física avançada": ["Mecânica quântica", "Física de partículas", "Teoria da Relatividade Geral", "Gravidade quântica", "Física de altas energias"],
    "termos de engenharia complexos": ["Circuitos integrados", "Engenharia genética", "Mecânica dos fluidos computacional", "Engenharia de materiais", "Robótica avançada"],
    "doenças genéticas raras": ["Síndrome de Marfan", "Síndrome de Rett", "Síndrome de Turner", "Doença de Wilson", "Síndrome de Lynch"],
    "pensadores contemporâneos": ["Slavoj Žižek", "Judith Butler", "Noam Chomsky", "Michel Foucault", "Cornel West"],
    "técnicas de pintura avançadas": ["Trompe-l'œil", "Sfumato", "Chiaroscuro", "Pointilism", "Impasto"],
    "termos de economia complexos": ["Teoria do Equilíbrio Geral", "Política Monetária", "Economia de Escala", "Multiplicador Keynesiano", "Oferta Agregada"],
    "cálculos matemáticos avançados": ["Integral de Lebesgue", "Transformada de Fourier", "Derivada direcional", "Teorema de Stokes", "Equações diferenciais parciais"],
    "termos de biologia molecular": ["Epigenética", "Transcrição reversa", "Splicing alternativo", "Sequenciamento de nova geração", "Reação em cadeia da polimerase"],
    "conceitos de psicologia profunda": ["Inconsciente coletivo", "Arquétipos", "Complexo de Édipo", "Mecanismos de defesa", "Teoria da Sombra"],
    "termos de teoria da música avançada": ["Polifonia", "Cromatismo", "Modulação", "Tessitura", "Contraponto"],
    "esculturas famosas": ["David de Michelangelo", "Pietà de Michelangelo", "O Pensador de Rodin", "Vênus de Milo", "Discóbolo de Míron"],
    "teorias de linguística": ["Sociolinguística", "Fonologia", "Morfologia", "Sintaxe", "Semântica"],
    "estilos de música erudita": ["Barroco", "Clássico", "Romântico", "Impressionista", "Contemporâneo"],
    "revoluções políticas": ["Revolução Francesa", "Revolução Russa", "Revolução Americana", "Revolução Cubana", "Revolução Chinesa"],
    "escolas filosóficas": ["Estoicismo", "Epicurismo", "Ceticismo", "Helenismo", "Cinismo"],
    "dinastias antigas": ["Dinastia Han", "Dinastia Zhou", "Dinastia Qin", "Dinastia Tang", "Dinastia Ming"],
    "grandes descobertas científicas": ["Teoria da Relatividade", "Lei da Gravitação Universal", "Eletromagnetismo", "Teoria da Evolução", "Teoria da Seleção Natural"],
    "teorias sociológicas": ["Funcionalismo", "Conflito", "Interação simbólica", "Estruturalismo", "Pós-modernismo"],
    "epopeias clássicas": ["Ilíada", "Odisseia", "Eneida", "Mahabharata", "Ramayana"]
  },
  "muito_dificil": {
    "complicações médicas raras": ["Encefalomielite", "Mielodisplasia", "Esclerose sistêmica", "Neurossífilis", "Poliomielite"],
    "teoremas matemáticos avançados": ["Teorema de Fermat", "Teorema de Gödel", "Teorema de Cantor", "Teorema de Euler", "Teorema de Poincaré"],
    "doenças neurodegenerativas raras": ["Doença de Creutzfeldt-Jakob", "Esclerose lateral amiotrófica", "Atrofia muscular espinhal", "Doença de Huntington", "Síndrome de Guillain-Barré"],
    "instrumentos musicais complexos": ["Theremim", "Ondes Martenot", "Clavicórdio", "Serrote musical", "Órgão de tubos"],
    "termos de astrofísica avançada": ["Buraco negro supermassivo", "Hipernova", "Quasar", "Pulsar", "Efeito Shapiro"],
    "desordens psiquiátricas complexas": ["Transtorno de personalidade esquizotípica", "Transtorno dissociativo de identidade", "Transtorno de personalidade borderline", "Transtorno bipolar do humor", "Esquizofrenia"],
    "gêneros literários obscuros": ["Dadaísmo", "Oulipo", "Ficção especulativa", "Literatura transgressiva", "Realismo mágico"],
    "termos de engenharia aeroespacial": ["Aerodinâmica", "Propulsão a jato", "Mecânica orbital", "Materiais compósitos aeroespaciais", "Sistema de controle de voo"],
    "doenças autoimunes raras": ["Granulomatose de Wegener", "Síndrome de Goodpasture", "Doença de Behçet", "Doença de Addison", "Púrpura trombocitopênica idiopática"],
    "estilos arquitetônicos complexos": ["Brutalismo", "Deconstructivismo", "Construtivismo russo", "High-tech", "Expressionismo"],
    "teorias políticas obscuras": ["Anarquismo insurrecionalista", "Municipalismo libertário", "Autonomismo", "Neomarxismo", "Ecofascismo"],
    "conceitos de psicanálise profunda": ["Complexo de Édipo negativo", "Narcisismo primário", "Superego", "Pulsão de morte", "Identificação projetiva"],
    "termos de linguística avançada": ["Sociolinguística", "Fonologia generativa", "Teoria da relevância", "Morfologia lexical", "Sintaxe minimalista"],
    "teorias de antropologia complexa": ["Estruturalismo", "Funcionalismo", "Culturalismo", "Teoria do conflito", "Antropologia simbólica"],
    "invenções tecnológicas revolucionárias": ["Transístor", "Internet", "Penicilina", "Vacina", "Impressora 3D"],
    "paradigmas científicos disruptivos": ["Teoria da relatividade", "Teoria do Big Bang", "Teoria da evolução", "Teoria quântica", "Teoria heliocêntrica"],
    "teorias de filosofia política complexas": ["Utilitarismo", "Contratualismo", "Hedonismo", "Existencialismo", "Anarquismo ontológico"],
    "movimentos artísticos experimentais": ["Arte conceitual", "Arte minimalista", "Arte performática", "Arte cinética", "Arte cibernética"],
    "termos de biotecnologia avançada": ["Edição de genoma", "Clonagem terapêutica", "Biorreator", "Biotecnologia vegetal", "Terapia gênica"],
    "conceitos de filosofia da mente complexos": ["Dualismo interativo", "Funcionalismo", "Materialismo eliminativo", "Epifenomenalismo", "Neutral monism"],
    "crises econômicas históricas": ["Grande Depressão", "Crise do Petróleo", "Crise de 1929", "Crise financeira de 2008", "Crise do subprime"],
    "desastres naturais": ["Terremoto de Lisboa", "Erupção do Monte Vesúvio", "Tsunami no Oceano Índico", "Inundação do rio Amarelo", "Furacão Katrina"],
    "teorias quânticas": ["Entrelaçamento quântico", "Superposição quântica", "Emaranhamento quântico", "Túnel quântico", "Teorema de Bell"],
    "livros filosóficos complexos": ["Ser e Tempo", "O Ser e o Nada", "Fenomenologia do Espírito", "Investigações Lógicas", "A Vontade de Saber"],
    "descobertas astronômicas importantes": ["Leis de Kepler", "Lei da Gravitação Universal", "Descoberta dos anéis de Saturno", "Descoberta dos satélites de Júpiter", "Descoberta dos exoplanetas"],
    "marcos de arquitetura moderna": ["Sídney Opera House", "Guggenheim Museum Bilbao", "Torre Eiffel", "Empire State Building", "Casa da Ópera de Oslo"],
    "ideologias políticas complexas": ["Anarco-sindicalismo", "Comunismo de conselhos", "Socialismo libertário", "Democracia participativa", "Capitalismo de Estado"],
    "obras literárias desafiadoras": ["Ulisses", "Em Busca do Tempo Perdido", "Cem Anos de Solidão", "O Som e a Fúria", "O Apanhador no Campo de Centeio"],
    "guerras modernas": ["Segunda Guerra Mundial", "Guerra Fria", "Guerra do Vietnã", "Guerra do Golfo", "Guerra Civil Síria"],
    "problemas matemáticos não resolvidos": ["Conjectura de Goldbach", "Conjectura de Hodge", "Hipótese de Riemann", "Conjectura de Poincaré", "Conjectura de Birch e Swinnerton-Dyer"]
  }
};